title: Example
baseUri: https://api.example.com
traits: !include /traits.yaml
/jsonapi:
  is: [authorized-by-token]
  get:
    displayName: fetch
    description: Fetch list
    queryParameters:
      default:
        description: java reserved word "default"
      if:
        description: java reserved word "if"
      enumparam:
        description: enum parameter with one underscored
        enum: [one, 2, underscored_param, for]
      boolparam:
        description: boolean parameter
        type: boolean
      required_param:
        description: required string param
        type: string
        required: true
      with_default_param:
        description: param with default value
        type: string
        default: default value
      _dotted_param.0:
        description: param with dot and digit in name
    responses:
      200:
        body:
          application/json:
            schema: !include schemas/groupResp.json
  post:
    description: Создание группы
    body:
      application/json:
        schema: !include schemas/group.json
    responses:
      201:
        description: |
          Group is created
      409:
        description: Group is already exist
      422:
        description: Validation error
  /{uri_param}:
    uriParameters:
      uri_param:
        description: integer param
        type: integer
    delete:
      description: Deletion
      responses:
        200:
          description: Group is deleted
        422:
          description: Deletion is forbidden
    get:
      description: Get group data
    patch:
      description: Change group data
      body:
        application/json:
          schema: !include schemas/group.json
      responses:
        200:
          description: Data is changed.
        422:
          description: Validation error
          body:
            application/json:
              schema: !include schemas/messageResp.json
/rpc_api:
  description: Some rpc deep api
  /{uid}/:
    uriParameters:
      uid:
        description: integer param
        type: integer
    /info/:
      description: in the middle of the path - template, ends with slash
      get:    
  /password:
    displayName: password
    description: this lvl has display name
    /submit:
      displayName: submit
      description: |
        ## link
        https://wiki.example.com/auth/#initialization
      get:
        queryParameters:
          duplicated_param:
            description: this param duplicated in get and post
            required: true
      post:
        body:
          application/x-www-form-urlencoded:
            formParameters:
              duplicated_param:
                description: this param duplicated in post and get
              form_param:
                description: clean form param
              enumparam_in_form:
                description: enum parameter in form parameters should not became query parameter
                enum: [one, 2, underscored_param, for]